In [1]:
# Database used → MNIST Database.com

import numpy as np
import pandas as pd
from tensorflow.keras import datasets

datasets

<module 'keras.api.datasets' from '/usr/local/lib/python3.10/dist-packages/keras/api/datasets/__init__.py'>

In [2]:
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()
x_train.shape

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


(60000, 28, 28)

In [3]:
x_test.shape

(10000, 28, 28)

In [4]:
width, height = 28, 28
input_shape = (width, height, 1)
input_shape

(28, 28, 1)

In [5]:
x_train = x_train.reshape(x_train.shape[0], height, width, 1)
x_test = x_test.reshape(x_test.shape[0], height, width, 1)

x_train.shape

(60000, 28, 28, 1)

In [6]:
y_train.shape

(60000,)

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size = 0.1)

len(x_val)


6000

In [8]:
x_train = (x_train - x_train.mean()) / x_train.std()
x_val = (x_val - x_val.mean()) / x_val.std()
x_test = (x_test - x_test.mean()) / x_test.std()

x_train


array([[[[-0.42395404],
         [-0.42395404],
         [-0.42395404],
         ...,
         [-0.42395404],
         [-0.42395404],
         [-0.42395404]],

        [[-0.42395404],
         [-0.42395404],
         [-0.42395404],
         ...,
         [-0.42395404],
         [-0.42395404],
         [-0.42395404]],

        [[-0.42395404],
         [-0.42395404],
         [-0.42395404],
         ...,
         [-0.42395404],
         [-0.42395404],
         [-0.42395404]],

        ...,

        [[-0.42395404],
         [-0.42395404],
         [-0.42395404],
         ...,
         [-0.42395404],
         [-0.42395404],
         [-0.42395404]],

        [[-0.42395404],
         [-0.42395404],
         [-0.42395404],
         ...,
         [-0.42395404],
         [-0.42395404],
         [-0.42395404]],

        [[-0.42395404],
         [-0.42395404],
         [-0.42395404],
         ...,
         [-0.42395404],
         [-0.42395404],
         [-0.42395404]]],


       [[[-0.42395404],


In [9]:
y_train

array([3, 5, 1, ..., 1, 8, 7], dtype=uint8)

In [10]:
import tensorflow
import keras
num_labels = 10
y_train = keras.utils.to_categorical(y_train)
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [11]:
y_val= keras.utils.to_categorical(y_val)
y_test= keras.utils.to_categorical(y_test)

In [12]:
# MODEL
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Input, Conv2D, MaxPooling2D, AveragePooling2D

model = Sequential()
model.add(Conv2D(6, kernel_size = (5, 5), strides = (1, 1), activation = 'tanh', input_shape = (28, 28, 1)))
model.add(AveragePooling2D(pool_size = (2,2), strides = (1,1)))
model.add(Conv2D(16, kernel_size = (5, 5), strides = (1, 1), activation = 'tanh'))
model.add(AveragePooling2D(pool_size = (2,2), strides = (2, 2)))
model.add(Conv2D(120, kernel_size = (5, 5), strides = (1, 1), activation = 'tanh'))
model.add(Flatten())
model.add(Dense(84, activation = 'tanh'))
model.add(Dense(num_labels, activation = "softmax"))

model.summary()


/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 24, 24, 6)           │             156 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d (AveragePooling2D) │ (None, 23, 23, 6)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 19, 19, 16)          │           2,416 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d_1                  │ (None, 9, 9, 16)            │               0 │
│ (AveragePooling2D)                   │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 5, 5, 120)           │          48,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 3000)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 84)                  │         252,084 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │             850 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 303,626 (1.16 MB)

 Trainable params: 303,626 (1.16 MB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.compile(loss = keras.losses.categorical_crossentropy, optimizer = 'adam', metrics = ['accuracy'])
history = model.fit(x_train, y_train, batch_size = 32, epochs = 20, verbose = 1, validation_data = (x_val, y_val))

score = model.evaluate(x_test, y_test, verbose = 1)
score


Epoch 1/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 26s 10ms/step - accuracy: 0.9030 - loss: 0.3225 - val_accuracy: 0.9665 - val_loss: 0.1118
Epoch 2/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9699 - loss: 0.1017 - val_accuracy: 0.9783 - val_loss: 0.0781
Epoch 3/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9748 - loss: 0.0832 - val_accuracy: 0.9738 - val_loss: 0.0835
Epoch 4/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9789 - loss: 0.0701 - val_accuracy: 0.9778 - val_loss: 0.0785
Epoch 5/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9792 - loss: 0.0663 - val_accuracy: 0.9788 - val_loss: 0.0783
Epoch 6/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9811 - loss: 0.0602 - val_accuracy: 0.9785 - val_loss: 0.0698
Epoch 7/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9826 - loss: 0.0539 - val_accuracy: 0.9787 - val_loss: 0.0751
Epoch 8/20
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9836 - loss: 0.0522 

[0.04363243654370308, 0.9865999817848206]